### PR TITLE
Repo mirror edit suggestions

### PR DESCRIPTION
**Pull request by gmacgre**
Nothing too serious, just wanted to add some consistency in the formatting of the git commands in the terminal

### CODE REVIEW

**Comment by gmacgre** [comment]
The only issue I have with this (as well as the vscode remote extension and debugger instructions) is the inconsistency in the separation of the username and repo name for some of the git clone commands. Running the instructions as written, I needed to add `cdeccio/` as a username when referencing the upstream repository.

**Comment by cdeccio** [comment]
> The only issue I have with this (as well as the vscode remote extension and debugger instructions) is the inconsistency in the separation of the username and repo name for some of the git clone commands.

Grant - good point.  I actually went back and forth about whether to introduce another "variable" for this (i.e., "CLASS_REPO_NAME").  I opted for simplicity by keeping one less variable.  However, as you mention, it is inconsistent in the sense that "*_REPO_NAME" means the entire path in once sense and only the actual repo name in the other.

> Running the instructions as written, I needed to add `cdeccio/` as a username when referencing the upstream repository.

I was just about to say "I provided the repo name as "cdeccio/byu-cs324-w2023", but then I saw that I had omitted that from the instructions! 🤦 So I'm adding that now.  Maybe this alone addresses most of the concerns?

But all this being said, I wonder if I should change CLASS_REPO_NAME to CLASS_REPO_PATH, for more accuracy?

**Comment by cdeccio** [comment]
> Additionally, do we want to add a section about cloning their mirror onto the remote machines to keep their whole workflow off of their local machines? If so, I'm not sure if that should be in the remote extension section or in the mirror instructions.

I like this idea.  The one question/concern is whether to have the "upstream" in both places.  It's totally do-able, but it gets complicated really fast when you're maintaining two clones of two repos (upstream and origin).

**Comment by gmacgre** [comment]
> So I'm adding that now. Maybe this alone addresses most of the concerns?
> But all this being said, I wonder if I should change CLASS_REPO_NAME to CLASS_REPO_PATH, for more accuracy?

I think that addresses my main concerns for this pull, so I think it is fine. If you think CLASS_REPO_PATH for more accuracy can work great.

**Comment by cdeccio** [comment]
Thanks!  I'll think I'll leave it for now and will revisit it again in the future 😅

**Pull request closed without merging**
